substitutions:
  _IMAGE_NAME: europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/spanish-testing/spanish-testing

steps:
  # 1. Build image
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '$_IMAGE_NAME:$COMMIT_SHA', '.']

  # 2. Push image
  - name: gcr.io/cloud-builders/docker
    args: ['push', '$_IMAGE_NAME:$COMMIT_SHA']

  # 3. Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - spanish-testing
      - --image=$_IMAGE_NAME:$COMMIT_SHA
      - --region=europe-west1
      - --platform=managed
      - --allow-unauthenticated

images:
  - '$_IMAGE_NAME:$COMMIT_SHA'

options:
  # This satisfies the new Cloud Build requirement when a service account is set
  logging: CLOUD_LOGGING_ONLY
